name: 'Hello World'
description: 'Greet someone and record the time'
inputs: # input parameteres are stored as environment variables
  who-to-greet: # id of input
    description: 'who to greet'
    default: 'World'

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'